package cf.funge.aworldofplants.model.plant;

import cf.funge.aworldofplants.configuration.DynamoDBConfiguration;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = DynamoDBConfiguration.PLANT_HISTORY_TABLE_NAME)
public class PlantHistory {
    private String plantId;
    private String chartType;
    private long startTime;
    private long endTime;
    private float avg;
    private float max;
    private float min;

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "plantId")
    public String getPlantId() {
        return plantId;
    }

    public void setPlantId(String plantId) {
        this.plantId = plantId;
    }

    @DynamoDBAttribute(attributeName = "chartType")
    public String getChartType() {
        return chartType;
    }

    public void setType(String chartType) {
        this.chartType = chartType;
    }


    @DynamoDBAttribute(attributeName = "startTime")
    public long getStartTime() {
        return startTime;
    }

    public void setStartTime(long startTime) {
        this.startTime = startTime;
    }

    @DynamoDBAttribute(attributeName = "endTime")
    public long getEndTime() {
        return endTime;
    }

    public void setEndTime(long endTime) {
        this.endTime = endTime;
    }

    @DynamoDBAttribute(attributeName = "avg")
    public float getAvg() {
        return avg;
    }

    public void setAvg(float avg) {
        this.avg = avg;
    }

    @DynamoDBAttribute(attributeName = "max")
    public float getMax() {
        return max;
    }

    public void setMax(float max) {
        this.max = max;
    }

    @DynamoDBAttribute(attributeName = "min")
    public float getMin() {
        return min;
    }

    public void setMin(float min) {
        this.min = min;
    }
}
