package cf.funge.aworldofplants.model.plant;

import cf.funge.aworldofplants.configuration.DynamoDBConfiguration;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = DynamoDBConfiguration.PLANT_HISTORY_TABLE_NAME)
public class PlantHistory {
    private String plantId;
    private long startTime;
    private long endTime;
    private String avg;
    private String max;
    private String min;

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "plantId")
    public String getPlantId() {
        return plantId;
    }

    public void setPlantId(String plantId) {
        this.plantId = plantId;
    }

    @DynamoDBAttribute(attributeName = "startTime")
    public long getStartTime() {
        return startTime;
    }

    public void setStartTime(long startTime) {
        this.startTime = startTime;
    }

    @DynamoDBAttribute(attributeName = "endTime")
    public long getEndTime() {
        return endTime;
    }

    public void setEndTime(long endTime) {
        this.endTime = endTime;
    }

    @DynamoDBAttribute(attributeName = "avg")
    public String getAvg() {
        return avg;
    }

    public void setAvg(String avg) {
        this.avg = avg;
    }

    @DynamoDBAttribute(attributeName = "max")
    public String getMax() {
        return max;
    }

    public void setMax(String max) {
        this.max = max;
    }

    @DynamoDBAttribute(attributeName = "min")
    public String getMin() {
        return min;
    }

    public void setMin(String min) {
        this.min = min;
    }
}
